### PR TITLE
Added link #8 on IO and Monads

### PR DESCRIPTION
**Pull request by mango314**

### CODE REVIEW

**Comment by katychuang** [comment]
Great link! I'm thinking IO & monads are related to web development but not necessarily only useful for web dev, so perhaps it fits in a new section?

**Comment by mango314** [comment]
You are right.  This is a good link, but it's not about Web Development.  What could this new section be called?  

I think IO/Monads are important functional programming concept.  IO is not the only common monad `List` is also a monad.   We can take a  `number` or a `string` or anything and get a new type that is a list a list of them `[number]` or `[string]`
https://www.fpcomplete.com/school/starting-with-haskell/basics-of-haskell/13-the-list-monad

**Comment by katychuang** [comment]
Perhaps something vague like, "Important Concepts" could work?

**Comment by mango314** [comment]
What about important **functional** concepts?  Emphasizing this is _functional_ programming?

**Comment by katychuang** [comment]
Specificity is excellent. I assumed it was clear that the title of the repo + the focus on Haskell made it clear that the section would refer to functional programming but you're right that the reader may not think that as they glance at the TOC. 

I like "Important Functional Programming Concepts", which seems to be the most optimal concise and specific version - what do you think?

**Comment by mango314** [comment]
Monads are not specific to Haskell and yet every Haskell programmer needs to know about Monads.  This is really about the Haskell _implementation_ of general FP concepts.

How about **General Functional Programming Concepts** ?

**Comment by MonsieurCactus** [comment]
How about **General Functional Programming Concepts** ?

**Comment by katychuang** [comment]
**General Functional Programming Concepts** sounds great! :+1: 

How does this work on Github. Will you be able to edit this pull request with the changes or will you have to submit another?

**Comment by mango314** [comment]
I was able to edit this pull request.  Thanks Kat.

**Pull request merged**
