### PR TITLE
Create blaze-ihaskell.ipynb

### PR DESCRIPTION
**Pull request by mango314**
see http://nbviewer.ipython.org/github/MonsieurCactus/getting-started-with-haskell/blob/master/tutorials/blaze-ihaskell.ipynb

### CODE REVIEW

**Comment by katychuang** [comment]
Nice example usage of iHaskell. :+1:  Would you happen to have a description of how to install it?

**Comment by mango314** [comment]
As of today `cabal install ihaskell` should install `ihaskell 0.6.0` which is the backend for [iPython3](http://ipython.org/) aka "Jupyter"
- https://hackage.haskell.org/package/ihaskell-0.6.0.0

I had been fighting cabal for about 2 weeks.  Removing and reinstalling ghc several times.  I was able to install successfully yesterday by cloning the github and running `linux-install.sh` during NY Haskell Meetup

**Ubuntu** Very recent versions of `ghc` (such as 7.10)  or `cabal` (such as 1.22)  are available using `sudo apt-get install ghc-7.10.1` etc if you use this PPA https://launchpad.net/~hvr/+archive/ubuntu/ghc

**Comment by katychuang** [comment]
Hmm I don't see linux-install.sh from the [iHaskell repo](https://github.com/gibiansky/IHaskell), could it have changed since you last installed?

**Comment by mango314** [comment]
Looks like it's now called `ubuntu-install.sh`

**Pull request merged**
